// swift-tools-version: 5.8

// WARNING:
// This file is generated by Apple and modified for ClassSchedule.
// It is required for Swift Playgrounds on iPadOS and macOS.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "ClassSchedule",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "ClassSchedule",
            targets: ["AppModule"],
            bundleIdentifier: "com.fengfeng.classschedule",
            teamIdentifier: "",
            displayVersion: "1.1.0",
            bundleVersion: "11",
            appIcon: .placeholder(icon: .calendar),
            accentColor: .presetColor(.indigo),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            appCategory: .education,
            additionalInfoPlistContentFilePath: "AppInfo.plist"
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "Sources/AppModule"
        )
    ]
)
